import Foundation
import Combine

enum AppLanguage: String {
    case pt, en
}

private let strings: [AppLanguage: [String: String]] = [
    .pt: [
        "menuTitle": "Xadrez",
        "menuSubtitle": "Escolhe um modo para começar",
        "mode1v1": "1 vs 1",
        "mode1v1Desc": "Dois jogadores, mesmo ecrã",
        "modeBot": "Contra o Bot",
        "modeBotDesc": "Escolhe o nível da IA",
        "modeTutorial": "Tutorial",
        "modeTutorialDesc": "Aprende a jogar por níveis",
        "modeHelp": "Ajuda",
        "modeHelpDesc": "Regras e controlos",
        "chooseDifficulty": "Escolhe o nível do bot",
        "levelBeginner": "Iniciante",
        "levelEasy": "Fácil",
        "levelMedium": "Médio",
        "levelHard": "Difícil",
        "cancelBtn": "Cancelar",
        "blackPlayer": "Pretas",
        "whitePlayer": "Brancas",
        "moveHistory": "Histórico de Lances",
        "undoMove": "↩️ Voltar Atrás",
        "redoMove": "↪️ Avançar",
        "flipBoard": "Inverter",
        "newGame": "Novo Jogo",
        "backToMenu": "Menu",
        "prevLesson": "Anterior",
        "nextLesson": "Seguinte",
        "helpTitle": "Ajuda",
        "footerBy": "Desenvolvido por",
        "introTitle": "Xadrez",
        "introText": "Joga 1 vs 1, desafia o bot, aprende as regras e as estratégias — tudo num só tabuleiro.",
        "introSkip": "Saltar",
        "turnWhite": "Vez das Brancas",
        "turnBlack": "Vez das Pretas",
        "thinking": "O bot está a pensar…",
        "inCheck": "Xeque!",
        "resultCheckmateTitle": "Xeque-mate!",
        "resultCheckmateWhite": "As Brancas vencem.",
        "resultCheckmateBlack": "As Pretas vencem.",
        "resultStalemateTitle": "Tabuada por Afogamento",
        "resultStalemateText": "Nenhum jogador tem lances legais. O jogo termina empatado.",
        "resultDraw50Title": "Empate",
        "resultDraw50Text": "50 lances sem capturas nem movimento de peão.",
        "resultDrawRepTitle": "Empate",
        "resultDrawRepText": "A mesma posição repetiu-se três vezes.",
        "resultDrawMatTitle": "Empate",
        "resultDrawMatText": "Nenhum dos lados tem material suficiente para dar mate.",
        "promoTitle": "Promover peão a:",
        "lessonHintClick": "Toca numa peça para veres os seus movimentos.",
        "modeMultiplayer": "Multijogador",
        "modeMultiplayerDesc": "Joga online com um amigo",
        "mpTitle": "Multijogador Online",
        "mpNotConfigured": "O multijogador ainda não está configurado.",
        "mpQuickPlay": "⚡ Jogo Rápido",
        "mpQuickPlayDesc": "Entra logo e espera por um adversário — sem código.",
        "mpCreateRoom": "➕ Criar Sala",
        "mpJoinRoom": "🔑 Entrar numa Sala",
        "mpEnterCode": "Introduz o código da sala",
        "mpJoin": "Entrar",
        "mpWaitingTitle": "À espera de um adversário…",
        "mpShareLink": "Partilhar Link",
        "mpShareText": "Vem jogar Xadrez comigo!",
        "mpErrorNotFound": "Essa sala não existe.",
        "mpErrorFull": "Essa sala já está cheia.",
        "mpErrorFinished": "Essa partida já terminou.",
        "mpErrorLobbyFull": "Todas as salas rápidas estão ocupadas. Tenta criar uma sala normal.",
        "mpErrorGeneric": "Não foi possível entrar na sala. Verifica o código.",
        "mpOpponentOnline": "🟢 Adversário online",
        "mpOpponentOffline": "⚪ Adversário offline",
        "mpWaitingOpponent": "⏳ À espera do adversário…",
        "resignGame": "🏳️ Desistir",
        "resignConfirmTitle": "Desistir da partida?",
        "resignConfirmText": "Tens a certeza que queres desistir?",
        "chatTitle": "Chat",
        "chatPlaceholder": "Escreve uma mensagem…",
        "resultOpponentResignedTitle": "Vitória!",
        "resultOpponentResignedText": "O teu adversário desistiu da partida.",
        "resultYouResignedTitle": "Desististe",
        "resultYouResignedText": "Desististe da partida.",
    ],
    .en: [
        "menuTitle": "Chess",
        "menuSubtitle": "Choose a mode to begin",
        "mode1v1": "1 vs 1",
        "mode1v1Desc": "Two players, same screen",
        "modeBot": "Vs Bot",
        "modeBotDesc": "Choose the AI level",
        "modeTutorial": "Tutorial",
        "modeTutorialDesc": "Learn to play, level by level",
        "modeHelp": "Help",
        "modeHelpDesc": "Rules and controls",
        "chooseDifficulty": "Choose the bot's level",
        "levelBeginner": "Beginner",
        "levelEasy": "Easy",
        "levelMedium": "Medium",
        "levelHard": "Hard",
        "cancelBtn": "Cancel",
        "blackPlayer": "Black",
        "whitePlayer": "White",
        "moveHistory": "Move History",
        "undoMove": "↩️ Undo",
        "redoMove": "↪️ Redo",
        "flipBoard": "Flip",
        "newGame": "New Game",
        "backToMenu": "Menu",
        "prevLesson": "Previous",
        "nextLesson": "Next",
        "helpTitle": "Help",
        "footerBy": "Developed by",
        "introTitle": "Chess",
        "introText": "Play 1 vs 1, challenge the bot, learn the rules and strategy — all on one board.",
        "introSkip": "Skip",
        "turnWhite": "White to move",
        "turnBlack": "Black to move",
        "thinking": "The bot is thinking…",
        "inCheck": "Check!",
        "resultCheckmateTitle": "Checkmate!",
        "resultCheckmateWhite": "White wins.",
        "resultCheckmateBlack": "Black wins.",
        "resultStalemateTitle": "Stalemate",
        "resultStalemateText": "Neither player has a legal move. The game is a draw.",
        "resultDraw50Title": "Draw",
        "resultDraw50Text": "50 moves without a capture or pawn move.",
        "resultDrawRepTitle": "Draw",
        "resultDrawRepText": "The same position occurred three times.",
        "resultDrawMatTitle": "Draw",
        "resultDrawMatText": "Neither side has enough material to checkmate.",
        "promoTitle": "Promote pawn to:",
        "lessonHintClick": "Tap a piece to see how it moves.",
        "modeMultiplayer": "Multiplayer",
        "modeMultiplayerDesc": "Play online with a friend",
        "mpTitle": "Online Multiplayer",
        "mpNotConfigured": "Multiplayer isn't configured yet.",
        "mpQuickPlay": "⚡ Quick Play",
        "mpQuickPlayDesc": "Jump in and wait for an opponent — no code needed.",
        "mpCreateRoom": "➕ Create Room",
        "mpJoinRoom": "🔑 Join a Room",
        "mpEnterCode": "Enter the room code",
        "mpJoin": "Join",
        "mpWaitingTitle": "Waiting for an opponent…",
        "mpShareLink": "Share Link",
        "mpShareText": "Come play Chess with me!",
        "mpErrorNotFound": "That room doesn't exist.",
        "mpErrorFull": "That room is already full.",
        "mpErrorFinished": "That match has already ended.",
        "mpErrorLobbyFull": "All quick-play rooms are full right now. Try creating a normal room.",
        "mpErrorGeneric": "Couldn't join the room. Check the code.",
        "mpOpponentOnline": "🟢 Opponent online",
        "mpOpponentOffline": "⚪ Opponent offline",
        "mpWaitingOpponent": "⏳ Waiting for opponent…",
        "resignGame": "🏳️ Resign",
        "resignConfirmTitle": "Resign the game?",
        "resignConfirmText": "Are you sure you want to resign?",
        "chatTitle": "Chat",
        "chatPlaceholder": "Type a message…",
        "resultOpponentResignedTitle": "Victory!",
        "resultOpponentResignedText": "Your opponent resigned the game.",
        "resultYouResignedTitle": "You resigned",
        "resultYouResignedText": "You resigned the game.",
    ],
]

final class Loc: ObservableObject {
    static let shared = Loc()

    @Published var language: AppLanguage {
        didSet { UserDefaults.standard.set(language.rawValue, forKey: "xadrez-lang") }
    }

    private init() {
        let saved = UserDefaults.standard.string(forKey: "xadrez-lang")
        self.language = AppLanguage(rawValue: saved ?? "pt") ?? .pt
    }

    func toggle() {
        language = language == .pt ? .en : .pt
    }

    func t(_ key: String) -> String {
        strings[language]?[key] ?? strings[.pt]?[key] ?? key
    }
}
